# Generated by Django 2.2.3 on 2019-07-19 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=40)),
                ('technology', models.CharField(max_length=100)),
                ('gprs', models.BooleanField()),
                ('edge', models.BooleanField()),
                ('announced', models.BooleanField()),
                ('status', models.CharField(max_length=80)),
                ('weight', models.CharField(max_length=20)),
                ('sim', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=60)),
                ('size', models.CharField(max_length=30)),
                ('resolution', models.CharField(max_length=50)),
                ('card_slot', models.BooleanField()),
                ('loud_speaker', models.BooleanField()),
                ('wlan', models.CharField(max_length=100)),
                ('bluetooth', models.CharField(max_length=100)),
                ('usb', models.CharField(max_length=100)),
                ('battery_c', models.CharField(max_length=100)),
                ('sensor', models.CharField(max_length=100)),
                ('cup', models.CharField(max_length=100)),
                ('internal_memory', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rate_type', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=160)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
