# Generated by Django 2.2.3 on 2019-07-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='device_images/'),
        ),
    ]
