# Generated by Django 2.2.3 on 2019-07-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190723_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
