# Generated by Django 2.2.3 on 2019-07-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_device_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='total_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
