# Generated by Django 2.2.3 on 2019-07-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_comment_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
