# Generated by Django 2.2.3 on 2019-07-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190724_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='announced',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='card_slot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='edge',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='gprs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='loud_speaker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='resolution',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='sim',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
