# Generated by Django 2.1.3 on 2019-07-20 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_device_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='usb',
            new_name='cpu',
        ),
    ]
