# Generated by Django 2.2.3 on 2019-07-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190720_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='announced',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='card_slot',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='edge',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='gprs',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='loud_speaker',
            field=models.CharField(max_length=50),
        ),
    ]
