# Generated by Django 2.2.3 on 2019-07-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190722_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='cup',
            new_name='gpu',
        ),
    ]
