# Generated by Django 2.2.3 on 2019-07-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190722_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
