# Generated by Django 2.2.3 on 2019-07-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190723_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='total_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
