# Generated by Django 2.2.3 on 2019-07-24 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190723_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Rate'),
            preserve_default=False,
        ),
    ]
